package scaffold

import (
	"fmt"
	"io"
	"sort"
	"strings"

	tfjson "github.com/hashicorp/terraform-json"
)

// TypeInfo holds scaffold data for a single resource type.
type TypeInfo struct {
	ResourceType string
	Fields       map[string]string // field name → sample value (from plan)
	IDTemplate   string            // "TODO" for now; registry lookup is a future phase
}

// Generate deduplicates resources by type, collects a sample field set from
// the first occurrence of each type, and returns a list sorted by type name.
// formats is an optional map of resource type → import format string fetched
// from the provider registry. Pass nil to fall back to "TODO" for all types.
func Generate(resources []*tfjson.ResourceChange, formats map[string]string) []TypeInfo {
	seen := make(map[string]*TypeInfo)
	var order []string

	for _, rc := range resources {
		if rc == nil || rc.Change == nil {
			continue
		}

		rt := rc.Type
		if _, exists := seen[rt]; exists {
			continue
		}

		info := &TypeInfo{
			ResourceType: rt,
			Fields:       make(map[string]string),
			IDTemplate:   "TODO",
		}

		// Collect field names and one sample value from Change.After.
		if after, ok := rc.Change.After.(map[string]interface{}); ok {
			for k, v := range after {
				if v == nil {
					info.Fields[k] = ""
					continue
				}
				switch val := v.(type) {
				case string:
					info.Fields[k] = val
				case bool:
					info.Fields[k] = fmt.Sprintf("%v", val)
				case float64:
					if val == float64(int64(val)) {
						info.Fields[k] = fmt.Sprintf("%d", int64(val))
					} else {
						info.Fields[k] = fmt.Sprintf("%g", val)
					}
				default:
					// skip complex nested types
				}
			}
		}

		// If a registry format was fetched for this type, convert it to a template.
		if formats != nil {
			if regFmt, ok := formats[rt]; ok && regFmt != "" {
				info.IDTemplate = FormatToTemplate(regFmt, info.Fields)
			}
		}

		seen[rt] = info
		order = append(order, rt)
	}

	sort.Strings(order)

	result := make([]TypeInfo, 0, len(order))
	for _, rt := range order {
		result = append(result, *seen[rt])
	}
	return result
}

// RenderYAML writes a scaffold YAML config to w, grouped by provider.
func RenderYAML(w io.Writer, types []TypeInfo) error {
	if len(types) == 0 {
		_, err := fmt.Fprintln(w, "# No resource types found in plan.")
		return err
	}

	// Group by provider, preserving sorted order within each group.
	providerOrder := []string{}
	byProvider := make(map[string][]TypeInfo)
	for _, ti := range types {
		p := ProviderFromType(ti.ResourceType)
		if _, exists := byProvider[p]; !exists {
			providerOrder = append(providerOrder, p)
		}
		byProvider[p] = append(byProvider[p], ti)
	}

	fmt.Fprintln(w, "# Generated by terra-import scaffold")
	fmt.Fprintln(w, "# Run: terra-import scaffold --plan <plan.json> -o config.yaml")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "vars: {}")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "types:")

	for _, provider := range providerOrder {
		group := byProvider[provider]
		fmt.Fprintf(w, "  # Provider: %s\n", provider)

		for _, ti := range group {
			// Build the available-fields comment.
			if len(ti.Fields) > 0 {
				fieldNames := make([]string, 0, len(ti.Fields))
				for k := range ti.Fields {
					fieldNames = append(fieldNames, k)
				}
				sort.Strings(fieldNames)

				parts := make([]string, 0, len(fieldNames))
				for _, k := range fieldNames {
					v := ti.Fields[k]
					if v == "" {
						parts = append(parts, fmt.Sprintf(".%s = (null)", k))
					} else {
						parts = append(parts, fmt.Sprintf(".%s = %q", k, v))
					}
				}
				fmt.Fprintf(w, "  %s:\n", ti.ResourceType)
				fmt.Fprintf(w, "    # Available fields: %s\n", strings.Join(parts, ", "))
			} else {
				fmt.Fprintf(w, "  %s:\n", ti.ResourceType)
				fmt.Fprintf(w, "    # Available fields: (none)\n")
			}
			fmt.Fprintf(w, "    id: %q\n", ti.IDTemplate)
		}
	}

	return nil
}
